excluded:
  - Carthage
  - Pods
  - .build
  - Tuist
  - Modules/**/Derived/**
  - helpers
  - fastlane/**
  - DerivedData
  - .swiftpm
  - Packages
  - ExternalPackages
  - Generated
  - GeneratedSources

   disabled_rules:
    - function_body_length