name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: macos-15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.4.app/Contents/Developer
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true
        
    - name: Setup Mise
      uses: jdx/mise-action@v2
      
    - name: Cache Tuist
      uses: actions/cache@v4
      with:
        path: |
          ~/.tuist
          ~/Library/Caches/tuist
        key: ${{ runner.os }}-tuist-${{ hashFiles('**/Tuist.swift', '**/Project.swift') }}
        restore-keys: |
          ${{ runner.os }}-tuist-
          
    - name: Install Tuist via mise
      run: |
        mise install tuist@4.50.2
        mise global tuist@4.50.2
        
    - name: Clear SPM cache
      run: |
        rm -rf ~/Library/Developer/Xcode/DerivedData
        rm -rf ~/Library/Caches/org.swift.swiftpm
        
    - name: Generate Xcode project
      run: tuist generate
        
    - name: Run Fastlane CI
      run: bundle exec fastlane ci
      
  lint:
    name: SwiftLint
    runs-on: macos-15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Run SwiftLint
      run: swiftlint lint --strict --config .swiftlint.ci.yml
